### ISSUE TITLE
Random errors

### ISSUE THREAD

**Issue by codingMASTER398** [Fabricio-191/youtube#8]
I use this package a lot, and have witnessed some random errors popping up on occasion, from reading "title" from undefined on video.js line 27 to things to do with "defaultText" (don't have an error on hand to show)

It also seems that recently the reading "title" from undefined has shot up, with nearly all requests resulting in that from many different IPs.

Please keep this package maintained! I use it a ton and an upcoming project of mine needs it as an essential element. Love your work!

**Comment by Fabricio-191** [comment]
If you could send me a consistent way of re-creating these errors it would help a lot, like video URL and your location/languaje (the module options) this is because for example if the video is not available in your country i need to know from what country you are to recreate the error

**Comment by Fabricio-191** [comment]
I updated it now, the "defaultText" error will not show anymore, in the worst case "likes" property could be null in the returned data

The "reading "title" from undefined on video.js line 27" will still be thrown as "Error getting data from youtube" and will give you extra data so you can send it to me, i could not replicate it

**Comment by codingMASTER398** [comment]
Thank you for this!

I'm going to school currently but tonight I'll see if it has been fixed, and if not, send you more details on them.

**Comment by codingMASTER398** [comment]
Hi,

At school now, have the errors on-hand.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/55938439/195453495-2b6ca348-25a5-44ac-b35f-6cc91e63f08f.png">

Most of the logs here are specific to my code, but when I run:
```js
getVideo(media["yt"])
      .then(async data => {
          // code
      })
```
It returns the error you can see, "Cannot read property of undefined (reading 'title')"

Here's the config:
```js
const { getVideo, search } = require('@fabricio-191/youtube')
  .setDefaultOptions({
    location: 'US',
    language: 'en-us'
  });
```

I'm also sending requests to the endpoint every 500ms or so and changing the IP on ratelimits.

**Comment by codingMASTER398** [comment]
This also happens on Runkit
<img width="420" alt="image" src="https://user-images.githubusercontent.com/55938439/195454626-ce443a6e-7476-4002-a69a-a36bcaeee20b.png">

**Comment by Fabricio-191** [comment]
I think i found the issue, when you open a youtube video like [this](https://www.youtube.com/watch?v=bBAZ3JpaosE) in your computer is there a thing that says `Upcoming events` ? and continues like this:
`Google has partnered with official 3rd party sellers listed below to show you ticketed events relating to the channel or content used in the video. The links and information listed below are from those sellers and may change. For a given event, if there are multiple sellers, the sellers are listed in alphabetical order. Click on links for more information and to buy from these sellers’ sites. Your activities and purchases made on 3rd party sellers’ sites are governed by the seller’s terms and conditions (including their privacy policies). The creator, channel, or content owner may receive compensation from these links.`

in my computer that doesn't happen even with the `{
    location: 'US',
    language: 'en-us'
  }` options, i think it's because youtube IP geolocalization, when anyone request a video or something in the return payload there is his real geolocalization

And that thing of  `Upcoming events` is occupying the place where the main video info should be, i will solve this promptly

![Screenshot_1](https://user-images.githubusercontent.com/47196132/195472259-598d00b7-af85-4041-9711-02bcae8afd4b.png)

**Comment by Fabricio-191** [comment]
Done, could you test it and tell me ? https://www.npmjs.com/package/@fabricio-191/youtube/v/0.0.3-2

**Comment by codingMASTER398** [comment]
![image](https://user-images.githubusercontent.com/55938439/195510581-e84c14ca-7d2a-410e-b26c-bf5d3e460964.png)
Still occurs, now in all languages.

**Comment by codingMASTER398** [comment]
Code for reference:
```js
const { getVideo, getPlaylist, search } = require('@fabricio-191/youtube')
  .setDefaultOptions({
    location: 'US',
    language: 'en-us'
  });
  
getVideo('bBAZ3JpaosE')
  .then(data => {
    console.log(data);
    //do something...
  })  
  .catch(console.error);
```

**Comment by Fabricio-191** [comment]
The problem with runkit is that it's using and old version of my module 0.0.3, i solved it in the version 0.0.3-2

Well, i'm going to close the issue, from my POV it's solved

Update the module in your code to the version 0.0.3-2 if any of these errors reapears reopen the issue
